Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Enabled: true
  Max: 25 # Lots of long block methods

Metrics/AbcSize:
  Enabled: true
  Max: 25
