name: rspec

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

    env:
      GEMFILE_RUBY_VERSION: 3.0.1
      SERVER_IDENTIFIER: ${{ secrets.SERVER_IDENTIFIER }}

    steps:
      - uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          # Not needed with a .ruby-version file
          ruby-version: 3.0.1
          # runs 'bundle install' and caches installed gems automatically
          bundler-cache: true

      - name: Run sorbet tc
        run: bundle exec srb tc

      - name: Run rubocop
        run: bundle exec rubocop

      - name: Run tests
        run: bundle exec rspec spec
